# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: f:/cpu-design/lab2/miniRV_pipeline_axi/src/rtl/ip/LED/LED.xci
# IP: The module: 'LED' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: f:/cpu-design/lab2/miniRV_pipeline_axi/src/rtl/ip/LED/LED_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'LED'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: f:/cpu-design/lab2/miniRV_pipeline_axi/src/rtl/ip/LED/LED_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'LED'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: f:/cpu-design/lab2/miniRV_pipeline_axi/src/rtl/ip/LED/LED.xdc
# XDC: The top module name and the constraint reference have the same name: 'LED'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: f:/cpu-design/lab2/miniRV_pipeline_axi/src/rtl/ip/LED/LED.xci
# IP: The module: 'LED' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: f:/cpu-design/lab2/miniRV_pipeline_axi/src/rtl/ip/LED/LED_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'LED'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: f:/cpu-design/lab2/miniRV_pipeline_axi/src/rtl/ip/LED/LED_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'LED'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: f:/cpu-design/lab2/miniRV_pipeline_axi/src/rtl/ip/LED/LED.xdc
# XDC: The top module name and the constraint reference have the same name: 'LED'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
