# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: f:/cpu-design/lab2/miniRV_pipeline_axi/src/rtl/ip/axi_protocol_converter_4/axi_protocol_converter_4.xci
# IP: The module: 'axi_protocol_converter_4' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: f:/cpu-design/lab2/miniRV_pipeline_axi/src/rtl/ip/axi_protocol_converter_4/axi_protocol_converter_4_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'axi_protocol_converter_4'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: f:/cpu-design/lab2/miniRV_pipeline_axi/src/rtl/ip/axi_protocol_converter_4/axi_protocol_converter_4.xci
# IP: The module: 'axi_protocol_converter_4' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: f:/cpu-design/lab2/miniRV_pipeline_axi/src/rtl/ip/axi_protocol_converter_4/axi_protocol_converter_4_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'axi_protocol_converter_4'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
