# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: F:/cpu-design/lab1/miniRV_basic_ego1/miniRV_basic/src/rtl/ip/DRAM/DRAM.xci
# IP: The module: 'DRAM' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: f:/cpu-design/lab1/miniRV_basic_ego1/miniRV_basic/src/rtl/ip/DRAM/DRAM_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'DRAM'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: F:/cpu-design/lab1/miniRV_basic_ego1/miniRV_basic/src/rtl/ip/DRAM/DRAM.xci
# IP: The module: 'DRAM' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: f:/cpu-design/lab1/miniRV_basic_ego1/miniRV_basic/src/rtl/ip/DRAM/DRAM_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'DRAM'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
